query ($category: String){
  categories(filter: {
    title: {
      equals: $category
    }
  }) {
    products {
      id
      title
      price {
        currency {
          sign
        }
        price
        nettoPriceMode
      }
      imageGallery {
        thumb
      }
    }
  }
}